# Generated by Django 2.2.5 on 2020-03-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_code', models.CharField(db_index=True, max_length=20, verbose_name='print_code')),
                ('name', models.CharField(max_length=100, verbose_name='Print Name')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Print Description')),
                ('length', models.PositiveIntegerField(verbose_name='Print Length (cm)')),
                ('width', models.PositiveIntegerField(verbose_name='Print Width (cm)')),
                ('frame', models.BooleanField(verbose_name='Print Framed')),
                ('finish', models.CharField(choices=[('GLS', 'Gloss'), ('MAT', 'Matt')], default='GLS', max_length=3, verbose_name='Print Finish')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('image', models.ImageField(blank=True, upload_to='prints/%Y/%m/%d')),
                ('enable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='print.Category')),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
