# Generated by Django 2.2.5 on 2020-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='length',
            field=models.PositiveIntegerField(default=25, verbose_name='Print Length (cm)'),
        ),
        migrations.AlterField(
            model_name='print',
            name='print_code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Print Code'),
        ),
        migrations.AlterField(
            model_name='print',
            name='width',
            field=models.PositiveIntegerField(default=20, verbose_name='Print Width (cm)'),
        ),
    ]
