# Generated by Django 2.2.5 on 2020-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0002_auto_20200316_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='print',
            options={'ordering': ('-category',)},
        ),
        migrations.AddField(
            model_name='print',
            name='discount',
            field=models.PositiveIntegerField(default=25, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='print',
            name='promotion',
            field=models.CharField(choices=[('FEA', 'Featured'), ('SPE', 'Specials'), ('SAL', 'Sale'), ('NAN', 'None')], default='NAN', max_length=3, verbose_name='Print Promotion Status'),
        ),
        migrations.AlterField(
            model_name='print',
            name='image',
            field=models.ImageField(blank=True, upload_to='prints/'),
        ),
    ]
