# Generated by Django 2.2.5 on 2020-04-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0007_auto_20200403_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='prints/', verbose_name='Main Image')),
                ('image_tn', models.ImageField(blank=True, upload_to='prints/', verbose_name='Thumbnail Image')),
                ('name', models.CharField(max_length=100, verbose_name='Print Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Print Description')),
                ('enable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
