# Generated by Django 2.2.5 on 2020-04-05 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0008_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='sub_title',
            field=models.CharField(default=1, max_length=30, verbose_name='Sub Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Print Title'),
            preserve_default=False,
        ),
    ]
