# Generated by Django 2.2.5 on 2020-04-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0009_auto_20200405_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='name',
        ),
    ]
