# Generated by Django 2.2.5 on 2020-04-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0010_auto_20200405_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='print_right',
            field=models.BooleanField(default=True),
        ),
    ]
