# Generated by Django 2.2.5 on 2020-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0011_gallery_print_right'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Print Category', 'verbose_name_plural': 'Print Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Home Gallery Image', 'verbose_name_plural': 'Home Gallery Images'},
        ),
        migrations.AlterField(
            model_name='print',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Print Name'),
        ),
    ]
