# Generated by Django 2.2.5 on 2020-04-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provice',
            field=models.CharField(blank=True, max_length=2, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='order',
            name='suburb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Suburb'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('COL', 'Collect'), ('COR', 'Courrier'), ('DRP', 'Drop Off')], default='COL', max_length=3, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method_confirmation',
            field=models.BooleanField(default=False, verbose_name='Delivery Method Confirmation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Postal Code'),
        ),
    ]
